### ISSUE TITLE
not working as expected

### ISSUE THREAD

**Issue by wowfrank** [webeks/octobercms-imageking#3] opened 2017-02-06 04:46 UTC
I was expecting some plugin to add watermark to blog images. For the first time loading, it took ages to load images from a post, and images were loaded with the watermark successfully. I have not checked the source code yet, but I guess it was creating new images that with watermarks. However, when I refreshed the page (actually any page), the watermark was gone forever. pretty wierd.

**Comment by webeks** [comment] 2017-02-06 10:34
Hi Frank

How many images per post do you have? How big are they?
What happens if you disable cache?

I think I was able to reproduce the bug, let me check ...

**Comment by webeks** [comment] 2017-02-06 10:53
Ok I think I fixed the problem. 

It is pushed to master and waiting to be deployed to OctoberCMS repository.

If you wish you can modify code by hand as shown in commit https://github.com/webeks/octobercms-imageking/commit/2c58371c709eb5f8f84d07304a64356f4365bb53


Let me know if it works :)

**Comment by webeks** [comment] 2017-02-20 12:45
since no reply I will assume this works now ... closing.

**Closed as completed by webeks** 2017-02-20 12:45 UTC
